// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7VFcoaJH1TUrP_IK17W-DuxAkpcP-jdw',
    appId: '1:226205984188:web:0deb24bd14c287f01ab7b9',
    messagingSenderId: '226205984188',
    projectId: 'smarthome-43dd2',
    authDomain: 'smarthome-43dd2.firebaseapp.com',
    storageBucket: 'smarthome-43dd2.appspot.com',
    measurementId: 'G-1MQH0J27H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7gCdSr5Ed-vScGOjB9CLY0smboBWUQlU',
    appId: '1:226205984188:android:a9a235437f4cceb21ab7b9',
    messagingSenderId: '226205984188',
    projectId: 'smarthome-43dd2',
    storageBucket: 'smarthome-43dd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXtlulBvF_DvZ90gdP94b71akgNadj4R0',
    appId: '1:226205984188:ios:1eb8b8198018c1f31ab7b9',
    messagingSenderId: '226205984188',
    projectId: 'smarthome-43dd2',
    storageBucket: 'smarthome-43dd2.appspot.com',
    iosClientId:
        '226205984188-b1smhbtcgdr9frl42stgnrb5fsh1kig4.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXtlulBvF_DvZ90gdP94b71akgNadj4R0',
    appId: '1:226205984188:ios:1eb8b8198018c1f31ab7b9',
    messagingSenderId: '226205984188',
    projectId: 'smarthome-43dd2',
    storageBucket: 'smarthome-43dd2.appspot.com',
    iosClientId:
        '226205984188-b1smhbtcgdr9frl42stgnrb5fsh1kig4.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );
}
